//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultiImage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFMultiImage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutBoxWindowTitle {
            get {
                return ResourceManager.GetString("AboutBoxWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By:.
        /// </summary>
        public static string AboutBy {
            get {
                return ResourceManager.GetString("AboutBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha:.
        /// </summary>
        public static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits Per Pixel:.
        /// </summary>
        public static string BitsPerPixel {
            get {
                return ResourceManager.GetString("BitsPerPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue:.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot be found.
        /// </summary>
        public static string CannotBeFound {
            get {
                return ResourceManager.GetString("CannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All.
        /// </summary>
        public static string CloseAll {
            get {
                return ResourceManager.GetString("CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All Images.
        /// </summary>
        public static string CloseAllImages {
            get {
                return ResourceManager.GetString("CloseAllImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close This Image.
        /// </summary>
        public static string CloseThisImage {
            get {
                return ResourceManager.GetString("CloseThisImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Next Image.
        /// </summary>
        public static string DisplayNextImage {
            get {
                return ResourceManager.GetString("DisplayNextImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Previous Image.
        /// </summary>
        public static string DisplayPreviousImage {
            get {
                return ResourceManager.GetString("DisplayPreviousImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time:.
        /// </summary>
        public static string fiCreationTime {
            get {
                return ResourceManager.GetString("fiCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name:.
        /// </summary>
        public static string fiFullName {
            get {
                return ResourceManager.GetString("fiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Write Time:.
        /// </summary>
        public static string fiLastWriteTime {
            get {
                return ResourceManager.GetString("fiLastWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size In Bytes:.
        /// </summary>
        public static string fiSizeInBytes {
            get {
                return ResourceManager.GetString("fiSizeInBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green:.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string HideBtn {
            get {
                return ResourceManager.GetString("HideBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Statistics.
        /// </summary>
        public static string HideBtnTooltip {
            get {
                return ResourceManager.GetString("HideBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index:.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on list for details!.
        /// </summary>
        public static string lstClickOnForDetails {
            get {
                return ResourceManager.GetString("lstClickOnForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPFMultiImage.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masks:.
        /// </summary>
        public static string Masks {
            get {
                return ResourceManager.GetString("Masks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name:.
        /// </summary>
        public static string mdApplicationName {
            get {
                return ResourceManager.GetString("mdApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string mdAuthor {
            get {
                return ResourceManager.GetString("mdAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Manufacturer:.
        /// </summary>
        public static string mdCameraManufacturer {
            get {
                return ResourceManager.GetString("mdCameraManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Model:.
        /// </summary>
        public static string mdCameraModel {
            get {
                return ResourceManager.GetString("mdCameraModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        public static string mdComment {
            get {
                return ResourceManager.GetString("mdComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright:.
        /// </summary>
        public static string mdCopyright {
            get {
                return ResourceManager.GetString("mdCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Taken:.
        /// </summary>
        public static string mdDateTaken {
            get {
                return ResourceManager.GetString("mdDateTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        public static string mdFormat {
            get {
                return ResourceManager.GetString("mdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords:.
        /// </summary>
        public static string mdKeywords {
            get {
                return ResourceManager.GetString("mdKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string mdLocation {
            get {
                return ResourceManager.GetString("mdLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating:.
        /// </summary>
        public static string mdRating {
            get {
                return ResourceManager.GetString("mdRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        public static string mdSubject {
            get {
                return ResourceManager.GetString("mdSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string mdTitle {
            get {
                return ResourceManager.GetString("mdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string mnuAbout {
            get {
                return ResourceManager.GetString("mnuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string mnuExit {
            get {
                return ResourceManager.GetString("mnuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string mnuFile {
            get {
                return ResourceManager.GetString("mnuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string mnuOpen {
            get {
                return ResourceManager.GetString("mnuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open Scenario.
        /// </summary>
        public static string mnuOpenScenario {
            get {
                return ResourceManager.GetString("mnuOpenScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save Scenario.
        /// </summary>
        public static string mnuSaveScenario {
            get {
                return ResourceManager.GetString("mnuSaveScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Scenario.
        /// </summary>
        public static string mnuScenario {
            get {
                return ResourceManager.GetString("mnuScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are already images open!.
        /// </summary>
        public static string msAlreadyImages {
            get {
                return ResourceManager.GetString("msAlreadyImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append the scenario(s) to the current image(s).
        /// </summary>
        public static string msAppend {
            get {
                return ResourceManager.GetString("msAppend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t open the scenario(s).
        /// </summary>
        public static string msCancel {
            get {
                return ResourceManager.GetString("msCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the current image(s) and open the scenario(s) chosen.
        /// </summary>
        public static string msClearAndOpen {
            get {
                return ResourceManager.GetString("msClearAndOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What shall I do?.
        /// </summary>
        public static string msWhatToDo {
            get {
                return ResourceManager.GetString("msWhatToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiImage.
        /// </summary>
        public static string MultiImage {
            get {
                return ResourceManager.GetString("MultiImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all images as one .TIF.
        /// </summary>
        public static string MultiImageTooltip {
            get {
                return ResourceManager.GetString("MultiImageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Palette.
        /// </summary>
        public static string NoPaletteTitle {
            get {
                return ResourceManager.GetString("NoPaletteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;not supported&gt;.
        /// </summary>
        public static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*|Image Files (*.bmp;*.gif;*.ico;*.jpeg;*.jpg;*.png;*.tif;*.tiff)|*.bmp;*.gif;*.ico;*.jpeg;*.jpg;*.png,*.tif;*.tiff&quot;.
        /// </summary>
        public static string ofdFilter {
            get {
                return ResourceManager.GetString("ofdFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Scenario File.
        /// </summary>
        public static string OpenFileScenario {
            get {
                return ResourceManager.GetString("OpenFileScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image Files.
        /// </summary>
        public static string OpenImageFiles {
            get {
                return ResourceManager.GetString("OpenImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count:.
        /// </summary>
        public static string PaletteCount {
            get {
                return ResourceManager.GetString("PaletteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette.
        /// </summary>
        public static string PaletteTitle {
            get {
                return ResourceManager.GetString("PaletteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Format:.
        /// </summary>
        public static string PixelFormat {
            get {
                return ResourceManager.GetString("PixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red:.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Scenario File.
        /// </summary>
        public static string SaveFileScenario {
            get {
                return ResourceManager.GetString("SaveFileScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image.
        /// </summary>
        public static string SaveImage {
            get {
                return ResourceManager.GetString("SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image File.
        /// </summary>
        public static string SaveImageFile {
            get {
                return ResourceManager.GetString("SaveImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save This Image.
        /// </summary>
        public static string SaveThisImage {
            get {
                return ResourceManager.GetString("SaveThisImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMP (*.bmp)|*.bmp|GIF (*.gif)|*.gif|JPG (*.jpg)|*.jpg|PNG (*.png)|*.png|TIF (*.tif)|*.tif.
        /// </summary>
        public static string sfdFilter {
            get {
                return ResourceManager.GetString("sfdFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string ShowBtn {
            get {
                return ResourceManager.GetString("ShowBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Statistics.
        /// </summary>
        public static string ShowBtnTooltip {
            get {
                return ResourceManager.GetString("ShowBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size in DPI:.
        /// </summary>
        public static string SizeInDPI {
            get {
                return ResourceManager.GetString("SizeInDPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size In Inches:.
        /// </summary>
        public static string SizeInInches {
            get {
                return ResourceManager.GetString("SizeInInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size In Pixels:.
        /// </summary>
        public static string SizeInPixels {
            get {
                return ResourceManager.GetString("SizeInPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.txt)|*.txt;.
        /// </summary>
        public static string TextFiles {
            get {
                return ResourceManager.GetString("TextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        public static string x {
            get {
                return ResourceManager.GetString("x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string xOFy {
            get {
                return ResourceManager.GetString("xOFy", resourceCulture);
            }
        }
    }
}
